---
title: "DUS paper plots"
format:
  revealjs: 
    theme: [simple, custom_1.scss]
    incremental: true   
    slide-number: true
    chalkboard: true
    preview-links: auto
    margin: 0.07
    code-link: true
    code-line-numbers: false
    height: 900
    width: 1600
execute:
  echo: true
  eval: true
editor: visual
---
```{r, include=FALSE}
library(omopgenerics)
library(DrugUtilisation)
library(ggh4x)
library(ggplot2)
library(flextable)
fileData <- file.path(getwd(), "data", "shinyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "data", "preprocess.R"))
}

load(fileData)


```



```{r}
bd <- fp_border(color = "black", width = .4)
df_restart <- data$summarise_drug_restart
tableDrugRestart(df_restart|>filterStrata(age_group == "overall", sex == "Female"),
                 header = c("cdm_name"),
                 hide = c("cohort_name", "cohort_table_name", "censor_date", "incident",
                          "restrict_to_first_discontinuation","switch_cohort_table",
                          "age_group", "follow_up_days", "sex"),
                 type = "flextable")|>
  theme_booktabs() |> # keep grey header only
  fontsize(part = "all", size = 8) |>
  padding(part = "all", padding = 2) |>
  autofit() |>
  border_remove() |>
  border_outer(border = bd) |>
  border_inner_h(border = bd) |>
  border_inner_v(border = bd) |>
  set_table_properties(width = .9) |>
  save_as_docx(tbl, path = paste0(getwd(), "/drug_restart_table.docx"))
```


```{r}
df_dus <- data$summarise_drug_utilisation
library(flextable)
library(officer)

tbl <- tableDrugUtilisation(
  df_dus |>
    filter(variable_name %in% c("number records", "number subjects", "number exposures")) |>
    filterStrata(sex == "overall", age_group != "overall"),
  groupColumn = "age_group",
  hide = c(
    "censor_date", "cohort_table_name", "gap_era", "index_date",
    "restrict_incident", "ingredient", "variable_level", "concept_set",
    "sex", "cohort_name"
  ),
  type = "flextable"
) |>
  theme_booktabs() |> # keep grey header only
  fontsize(part = "all", size = 8) |>
  padding(part = "all", padding = 2) |>
  autofit() |>
  border_remove() |>
  border_outer(border = bd) |>
  border_inner_h(border = bd) |>
  border_inner_v(border = bd) |>
  set_table_properties(width = .9) |>
  save_as_docx(tbl, path = paste0(getwd(), "/drug_utilisation_table.docx"))

```


```{r}
df_de <- df_dus |> filter(variable_name == "days exposed")|>
filterStrata(sex %in% c("Female", "Male"), age_group != "overall")

plotDrugUtilisation(
  df_de,
  plotType = "boxplot",
  variable = "days exposed",
  facet    = cdm_name ~ sex,
  colour   = NULL
) +
  facet_grid(cdm_name ~ sex, scales = "free_y") +   # make y-scales free
  facetted_pos_scales(
    y = list(
      cdm_name == "MAITT" ~ scale_y_continuous(limits = c(0, 500)),
      TRUE                ~ scale_y_continuous(limits = c(0, 1000))
    )
  )+
  theme(text = element_text(size = 16))



```

```{r}
df_ind <- data$summarise_indication |>
  filterStrata(sex == "overall") |>
  filter(variable_name == "Indication on index date")

plotIndication(df_ind, facet = cdm_name~age_group)+
  theme(text = element_text(size = 16))
```
