# Generated by OmopViewer 0.2.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      omopgenerics::exportSummarisedResult(data, fileName = file)
    }
  )
  # summarise_omop_snapshot -----
  ## tidy summarise_omop_snapshot -----
  getTidyDataSummariseOmopSnapshot <- shiny::reactive({
    res <- data |>
      filterData("summarise_omop_snapshot", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_omop_snapshot_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_omop_snapshot_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseOmopSnapshot(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_omop_snapshot.csv",
    content = function(file) {
      getTidyDataSummariseOmopSnapshot() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_omop_snapshot -----
  ## output 17 -----
  createOutput17 <- shiny::reactive({
    result <- data |>
      filterData("summarise_omop_snapshot", input)
    OmopSketch::tableOmopSnapshot(
      result
    )
  })
  output$summarise_omop_snapshot_gt_17 <- gt::render_gt({
    createOutput17()
  })
  output$summarise_omop_snapshot_gt_17_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_omop_snapshot.", input$summarise_omop_snapshot_gt_17_download_type),
    content = function(file) {
      obj <- createOutput17()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_cohort_count -----
  ## tidy summarise_cohort_count -----
  getTidyDataSummariseCohortCount <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_count", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_count_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_count_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_count_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortCount(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_count_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_count.csv",
    content = function(file) {
      getTidyDataSummariseCohortCount() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_count -----
  ## output 9 -----
  createOutput9 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input)
    CohortCharacteristics::tableCohortCount(
      result,
      header = input$summarise_cohort_count_gt_9_header,
      groupColumn = input$summarise_cohort_count_gt_9_groupColumn,
      hide = input$summarise_cohort_count_gt_9_hide
    )
  })
  output$summarise_cohort_count_gt_9 <- gt::render_gt({
    createOutput9()
  })
  output$summarise_cohort_count_gt_9_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_count.", input$summarise_cohort_count_gt_9_download_type),
    content = function(file) {
      obj <- createOutput9()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 10 -----
  createOutput10 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_count", input)
    CohortCharacteristics::plotCohortCount(
      result,
      facet = input$summarise_cohort_count_ggplot2_10_facet,
      colour = input$summarise_cohort_count_ggplot2_10_colour
    )
  })
  output$summarise_cohort_count_ggplot2_10 <- shiny::renderPlot({
    createOutput10()
  })
  output$summarise_cohort_count_ggplot2_10_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_cohort_count.", "png"),
    content = function(file) {
      obj <- createOutput10()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_cohort_count_ggplot2_10_download_width),
        height = as.numeric(input$summarise_cohort_count_ggplot2_10_download_height),
        units = input$summarise_cohort_count_ggplot2_10_download_units,
        dpi = as.numeric(input$summarise_cohort_count_ggplot2_10_download_dpi)
      )
    }
  )


  # summarise_cohort_attrition -----
  ## tidy summarise_cohort_attrition -----
  
  getTidyDataSummariseCohortAttrition <- shiny::reactive({
    res <- data |>
      filterData("summarise_cohort_attrition", input)|>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_cohort_attrition_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_cohort_attrition_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_cohort_attrition_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCohortAttrition(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_cohort_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_cohort_attrition.csv",
    content = function(file) {
      getTidyDataSummariseCohortAttrition() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_cohort_attrition -----
  ## output 3 -----
  createOutput3 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::tableCohortAttrition(
      result,
      header = input$summarise_cohort_attrition_gt_3_header,
      groupColumn = input$summarise_cohort_attrition_gt_3_groupColumn,
      hide = input$summarise_cohort_attrition_gt_3_hide
    )
  })
  output$summarise_cohort_attrition_gt_3 <- gt::render_gt({
    createOutput3()
  })
  output$summarise_cohort_attrition_gt_3_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_cohort_attrition.", input$summarise_cohort_attrition_gt_3_download_type),
    content = function(file) {
      obj <- createOutput3()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 4 -----
  createOutput4 <- shiny::reactive({
    result <- data |>
      filterData("summarise_cohort_attrition", input)
    CohortCharacteristics::plotCohortAttrition(
      result
    )
  })
  output$summarise_cohort_attrition_grViz_4 <- DiagrammeR::renderGrViz({
    createOutput4()
  })
  output$summarise_cohort_attrition_grViz_4_download <- shiny::downloadHandler(
    filename = paste0("output_grViz_summarise_cohort_attrition.", "png"),
    content = function(file) {
      obj <- createOutput4()
      DiagrammeR::export_graph(
        graph = obj,
        file_name = file,
        fily_type = "png",
        width = as.numeric(input$summarise_cohort_attrition_grViz_4_download_width),
        height = as.numeric(input$summarise_cohort_attrition_grViz_4_download_height)
      )
    }
  )


  # prevalence -----
  ## tidy prevalence -----
  getTidyDataPrevalence <- shiny::reactive({
    res <- data |>
      filterData("prevalence", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$prevalence_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$prevalence_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$prevalence_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataPrevalence(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$prevalence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_prevalence.csv",
    content = function(file) {
      getTidyDataPrevalence() |>
        readr::write_csv(file = file)
    }
  )
  ## output prevalence -----
  ## output 20 -----
  createOutput20 <- shiny::reactive({
    result <- data |>
      filterData("prevalence", input)
    IncidencePrevalence::tablePrevalence(
      result,
      header = input$prevalence_gt_20_header,
      groupColumn = input$prevalence_gt_20_groupColumn,
      hide = input$prevalence_gt_20_hide
    )
  })
  output$prevalence_gt_20 <- gt::render_gt({
    createOutput20()
  })
  output$prevalence_gt_20_download <- shiny::downloadHandler(
    filename = paste0("output_gt_prevalence.", input$prevalence_gt_20_download_type),
    content = function(file) {
      obj <- createOutput20()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 21 -----
  createOutput21 <- shiny::reactive({
    result <- data |>
      filterData("prevalence", input)
    IncidencePrevalence::plotPrevalence(
      result,
      x = input$prevalence_ggplot2_21_x,
      ribbon = input$prevalence_ggplot2_21_ribbon,
      facet = input$prevalence_ggplot2_21_facet,
      colour = input$prevalence_ggplot2_21_colour
    )
  })
  output$prevalence_ggplot2_21 <- shiny::renderPlot({
    createOutput21()
  })
  output$prevalence_ggplot2_21_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_prevalence.", "png"),
    content = function(file) {
      obj <- createOutput21()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$prevalence_ggplot2_21_download_width),
        height = as.numeric(input$prevalence_ggplot2_21_download_height),
        units = input$prevalence_ggplot2_21_download_units,
        dpi = as.numeric(input$prevalence_ggplot2_21_download_dpi)
      )
    }
  )


  # prevalence_attrition -----
  ## tidy prevalence_attrition -----
  getTidyDataPrevalenceAttrition <- shiny::reactive({
    res <- data |>
      filterData("prevalence_attrition", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$prevalence_attrition_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$prevalence_attrition_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$prevalence_attrition_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataPrevalenceAttrition(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$prevalence_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_prevalence_attrition.csv",
    content = function(file) {
      getTidyDataPrevalenceAttrition() |>
        readr::write_csv(file = file)
    }
  )
  ## output prevalence_attrition -----
  ## output 23 -----
  createOutput23 <- shiny::reactive({
    result <- data |>
      filterData("prevalence_attrition", input)
    IncidencePrevalence::tablePrevalenceAttrition(
      result,
      header = input$prevalence_attrition_gt_23_header,
      groupColumn = input$prevalence_attrition_gt_23_groupColumn,
      hide = input$prevalence_attrition_gt_23_hide
    )
  })
  output$prevalence_attrition_gt_23 <- gt::render_gt({
    createOutput23()
  })
  output$prevalence_attrition_gt_23_download <- shiny::downloadHandler(
    filename = paste0("output_gt_prevalence_attrition.", input$prevalence_attrition_gt_23_download_type),
    content = function(file) {
      obj <- createOutput23()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # incidence -----
  ## tidy incidence -----
  getTidyDataIncidence <- shiny::reactive({
    res <- data |>
      filterData("incidence", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$incidence_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$incidence_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$incidence_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataIncidence(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$incidence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_incidence.csv",
    content = function(file) {
      getTidyDataIncidence() |>
        readr::write_csv(file = file)
    }
  )
  ## output incidence -----
  ## output 18 -----
  createOutput18 <- shiny::reactive({
    result <- data |>
      filterData("incidence", input)
    IncidencePrevalence::tableIncidence(
      result,
      header = input$incidence_gt_18_header,
      groupColumn = input$incidence_gt_18_groupColumn,
      hide = input$incidence_gt_18_hide
    )
  })
  output$incidence_gt_18 <- gt::render_gt({
    createOutput18()
  })
  output$incidence_gt_18_download <- shiny::downloadHandler(
    filename = paste0("output_gt_incidence.", input$incidence_gt_18_download_type),
    content = function(file) {
      obj <- createOutput18()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 19 -----
  createOutput19 <- shiny::reactive({
    result <- data |>
      filterData("incidence", input)
    IncidencePrevalence::plotIncidence(
      result,
      x = input$incidence_ggplot2_19_x,
      ribbon = input$incidence_ggplot2_19_ribbon,
      facet = input$incidence_ggplot2_19_facet,
      colour = input$incidence_ggplot2_19_colour
    )
  })
  output$incidence_ggplot2_19 <- shiny::renderPlot({
    createOutput19()
  })
  output$incidence_ggplot2_19_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_incidence.", "png"),
    content = function(file) {
      obj <- createOutput19()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$incidence_ggplot2_19_download_width),
        height = as.numeric(input$incidence_ggplot2_19_download_height),
        units = input$incidence_ggplot2_19_download_units,
        dpi = as.numeric(input$incidence_ggplot2_19_download_dpi)
      )
    }
  )


  # incidence_attrition -----
  ## tidy incidence_attrition -----
  getTidyDataIncidenceAttrition <- shiny::reactive({
    res <- data |>
      filterData("incidence_attrition", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$incidence_attrition_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$incidence_attrition_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$incidence_attrition_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataIncidenceAttrition(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$incidence_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_incidence_attrition.csv",
    content = function(file) {
      getTidyDataIncidenceAttrition() |>
        readr::write_csv(file = file)
    }
  )
  ## output incidence_attrition -----
  ## output 22 -----
  createOutput22 <- shiny::reactive({
    result <- data |>
      filterData("incidence_attrition", input)
    IncidencePrevalence::tableIncidenceAttrition(
      result,
      header = input$incidence_attrition_gt_22_header,
      groupColumn = input$incidence_attrition_gt_22_groupColumn,
      hide = input$incidence_attrition_gt_22_hide
    )
  })
  output$incidence_attrition_gt_22 <- gt::render_gt({
    createOutput22()
  })
  output$incidence_attrition_gt_22_download <- shiny::downloadHandler(
    filename = paste0("output_gt_incidence_attrition.", input$incidence_attrition_gt_22_download_type),
    content = function(file) {
      obj <- createOutput22()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_characteristics -----
  ## tidy summarise_characteristics -----
  getTidyDataSummariseCharacteristics <- shiny::reactive({
    res <- data |>
      filterData("summarise_characteristics", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_characteristics_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_characteristics_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseCharacteristics(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_characteristics.csv",
    content = function(file) {
      getTidyDataSummariseCharacteristics() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_characteristics -----
  ## output 7 -----
  createOutput7 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    CohortCharacteristics::tableCharacteristics(
      result,
      header = input$summarise_characteristics_gt_7_header,
      groupColumn = input$summarise_characteristics_gt_7_groupColumn,
      hide = input$summarise_characteristics_gt_7_hide
    )
  })
  output$summarise_characteristics_gt_7 <- gt::render_gt({
    createOutput7()
  })
  output$summarise_characteristics_gt_7_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_characteristics.", input$summarise_characteristics_gt_7_download_type),
    content = function(file) {
      obj <- createOutput7()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 8 -----
  createOutput8 <- shiny::reactive({
    result <- data |>
      filterData("summarise_characteristics", input)
    CohortCharacteristics::plotCharacteristics(
      result,
      plotStyle = input$summarise_characteristics_ggplot2_8_plotStyle,
      facet = input$summarise_characteristics_ggplot2_8_facet,
      colour = input$summarise_characteristics_ggplot2_8_colour
    )
  })
  output$summarise_characteristics_ggplot2_8 <- shiny::renderPlot({
    createOutput8()
  })
  output$summarise_characteristics_ggplot2_8_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_characteristics.", "png"),
    content = function(file) {
      obj <- createOutput8()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_characteristics_ggplot2_8_download_width),
        height = as.numeric(input$summarise_characteristics_ggplot2_8_download_height),
        units = input$summarise_characteristics_ggplot2_8_download_units,
        dpi = as.numeric(input$summarise_characteristics_ggplot2_8_download_dpi)
      )
    }
  )


  # summarise_indication -----
  ## tidy summarise_indication -----
  getTidyDataSummariseIndication <- shiny::reactive({
    res <- data |>
      filterData("summarise_indication", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    print(input)
    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_indication_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_indication_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_indication_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseIndication(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_indication_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_indication.csv",
    content = function(file) {
      getTidyDataSummariseIndication() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_indication -----
  ## output 28 -----
  createOutput28 <- shiny::reactive({
    result <- data |>
      filterData("summarise_indication", input)
    DrugUtilisation::tableIndication(
      result
    )
  })
  output$summarise_indication_gt_28 <- gt::render_gt({
    createOutput28()
  })
  output$summarise_indication_gt_28_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_indication.", input$summarise_indication_gt_28_download_type),
    content = function(file) {
      obj <- createOutput28()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 29 -----
  createOutput29 <- shiny::reactive({
    result <- data |>
      filterData("summarise_indication", input)
    DrugUtilisation::plotIndication(
      result
    )
  })
  output$summarise_indication_ggplot2_29 <- shiny::renderPlot({
    createOutput29()
  })
  output$summarise_indication_ggplot2_29_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_indication.", "png"),
    content = function(file) {
      obj <- createOutput29()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_indication_ggplot2_29_download_width),
        height = as.numeric(input$summarise_indication_ggplot2_29_download_height),
        units = input$summarise_indication_ggplot2_29_download_units,
        dpi = as.numeric(input$summarise_indication_ggplot2_29_download_dpi)
      )
    }
  )


  # summarise_drug_utilisation -----
  ## tidy summarise_drug_utilisation -----
  getTidyDataSummariseDrugUtilisation <- shiny::reactive({
    res <- data |>
      filterData("summarise_drug_utilisation", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_drug_utilisation_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_drug_utilisation_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_drug_utilisation_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseDrugUtilisation(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_drug_utilisation_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_drug_utilisation.csv",
    content = function(file) {
      getTidyDataSummariseDrugUtilisation() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_drug_utilisation -----
  ## output 27 -----
  createOutput27 <- shiny::reactive({
    result <- data |>
      filterData("summarise_drug_utilisation", input)
    DrugUtilisation::tableDrugUtilisation(
      result
    )
  })
  output$summarise_drug_utilisation_gt_27 <- gt::render_gt({
    createOutput27()
  })
  output$summarise_drug_utilisation_gt_27_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_drug_utilisation.", input$summarise_drug_utilisation_gt_27_download_type),
    content = function(file) {
      obj <- createOutput27()
      gt::gtsave(data = obj, filename = file)
    }
  )


  # summarise_proportion_of_patients_covered -----
  ## tidy summarise_proportion_of_patients_covered -----
  getTidyDataSummariseProportionOfPatientsCovered <- shiny::reactive({
    res <- data |>
      filterData("summarise_proportion_of_patients_covered", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_proportion_of_patients_covered_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_proportion_of_patients_covered_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_proportion_of_patients_covered_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseProportionOfPatientsCovered(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_proportion_of_patients_covered_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_proportion_of_patients_covered.csv",
    content = function(file) {
      getTidyDataSummariseProportionOfPatientsCovered() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_proportion_of_patients_covered -----
  ## output 30 -----
  createOutput30 <- shiny::reactive({
    result <- data |>
      filterData("summarise_proportion_of_patients_covered", input)
    DrugUtilisation::tableProportionOfPatientsCovered(
      result
    )
  })
  output$summarise_proportion_of_patients_covered_gt_30 <- gt::render_gt({
    createOutput30()
  })
  output$summarise_proportion_of_patients_covered_gt_30_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_proportion_of_patients_covered.", input$summarise_proportion_of_patients_covered_gt_30_download_type),
    content = function(file) {
      obj <- createOutput30()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 31 -----
  createOutput31 <- shiny::reactive({
    result <- data |>
      filterData("summarise_proportion_of_patients_covered", input)
    DrugUtilisation::plotProportionOfPatientsCovered(
      result
    )
  })
  output$summarise_proportion_of_patients_covered_ggplot2_31 <- shiny::renderPlot({
    createOutput31()
  })
  output$summarise_proportion_of_patients_covered_ggplot2_31_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_proportion_of_patients_covered.", "png"),
    content = function(file) {
      obj <- createOutput31()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_proportion_of_patients_covered_ggplot2_31_download_width),
        height = as.numeric(input$summarise_proportion_of_patients_covered_ggplot2_31_download_height),
        units = input$summarise_proportion_of_patients_covered_ggplot2_31_download_units,
        dpi = as.numeric(input$summarise_proportion_of_patients_covered_ggplot2_31_download_dpi)
      )
    }
  )


  # summarise_treatment -----
  ## tidy summarise_treatment -----
  getTidyDataSummariseTreatment <- shiny::reactive({
    res <- data |>
      filterData("summarise_treatment", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_treatment_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_treatment_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_treatment_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseTreatment(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_treatment_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_treatment.csv",
    content = function(file) {
      getTidyDataSummariseTreatment() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_treatment -----
  ## output 32 -----
  createOutput32 <- shiny::reactive({
    result <- data |>
      filterData("summarise_treatment", input)
    DrugUtilisation::tableTreatment(
      result
    )
  })
  output$summarise_treatment_gt_32 <- gt::render_gt({
    createOutput32()
  })
  output$summarise_treatment_gt_32_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_treatment.", input$summarise_treatment_gt_32_download_type),
    content = function(file) {
      obj <- createOutput32()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 33 -----
  createOutput33 <- shiny::reactive({
    result <- data |>
      filterData("summarise_treatment", input)
    DrugUtilisation::plotTreatment(
      result
    )
  })
  output$summarise_treatment_ggplot2_33 <- shiny::renderPlot({
    createOutput33()
  })
  output$summarise_treatment_ggplot2_33_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_treatment.", "png"),
    content = function(file) {
      obj <- createOutput33()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_treatment_ggplot2_33_download_width),
        height = as.numeric(input$summarise_treatment_ggplot2_33_download_height),
        units = input$summarise_treatment_ggplot2_33_download_units,
        dpi = as.numeric(input$summarise_treatment_ggplot2_33_download_dpi)
      )
    }
  )


  # summarise_drug_restart -----
  ## tidy summarise_drug_restart -----
  getTidyDataSummariseDrugRestart <- shiny::reactive({
    res <- data |>
      filterData("summarise_drug_restart", input) |>
      omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::select(!"result_id")

    # columns to eliminate
    colsEliminate <- colnames(res)
    colsEliminate <- colsEliminate[!colsEliminate %in% c(
      input$summarise_drug_restart_tidy_columns, "variable_name", "variable_level",
      "estimate_name", "estimate_type", "estimate_value"
    )]

    # pivot
    pivot <- input$summarise_drug_restart_tidy_pivot
    if (pivot != "none") {
      vars <- switch(pivot,
        "estimates" = "estimate_name",
        "estimates and variables" = c("variable_name", "variable_level", "estimate_name")
      )
      res <- res |>
        visOmopResults::pivotEstimates(pivotEstimatesBy = vars)
    }

    res |>
      dplyr::select(!dplyr::all_of(colsEliminate))
  })
  output$summarise_drug_restart_tidy <- DT::renderDT({
    DT::datatable(
      getTidyDataSummariseDrugRestart(),
      options = list(scrollX = TRUE),
      rownames = FALSE
    )
  })
  output$summarise_drug_restart_tidy_download <- shiny::downloadHandler(
    filename = "tidy_summarise_drug_restart.csv",
    content = function(file) {
      getTidyDataSummariseDrugRestart() |>
        readr::write_csv(file = file)
    }
  )
  ## output summarise_drug_restart -----
  ## output 25 -----
  createOutput25 <- shiny::reactive({
    result <- data |>
      filterData("summarise_drug_restart", input)
    DrugUtilisation::tableDrugRestart(
      result, hide = c("restrict_to_first_discontinuation", "follow_up_days")
    )
  })
  output$summarise_drug_restart_gt_25 <- gt::render_gt({
    createOutput25()
  })
  output$summarise_drug_restart_gt_25_download <- shiny::downloadHandler(
    filename = paste0("output_gt_summarise_drug_restart.", input$summarise_drug_restart_gt_25_download_type),
    content = function(file) {
      obj <- createOutput25()
      gt::gtsave(data = obj, filename = file)
    }
  )

  ## output 26 -----
  createOutput26 <- shiny::reactive({
    result <- data |>
      filterData("summarise_drug_restart", input)
    DrugUtilisation::plotDrugRestart(
      result
    )
  })
  output$summarise_drug_restart_ggplot2_26 <- shiny::renderPlot({
    createOutput26()
  })
  output$summarise_drug_restart_ggplot2_26_download <- shiny::downloadHandler(
    filename = paste0("output_ggplot2_summarise_drug_restart.", "png"),
    content = function(file) {
      obj <- createOutput26()
      ggplot2::ggsave(
        filename = file,
        plot = obj,
        width = as.numeric(input$summarise_drug_restart_ggplot2_26_download_width),
        height = as.numeric(input$summarise_drug_restart_ggplot2_26_download_height),
        units = input$summarise_drug_restart_ggplot2_26_download_units,
        dpi = as.numeric(input$summarise_drug_restart_ggplot2_26_download_dpi)
      )
    }
  )
}
